### ISSUE TITLE
cannot submit workdays due to missing dropdown in create workday modal

### ISSUE THREAD

**Issue by tkgroot** [flock-community/flock-eco-workday#227]
in the add workday modal there used to be a dropdown to select a subject to attach the workdays to. This is missing (see screenshot). This prevents the submit and closing of the modal.

<img width="781" alt="bugreport" src="https://user-images.githubusercontent.com/11505121/162004721-a418f1af-b360-4ffc-aef7-f3fba4c6e897.png">

**Comment by timsmelik** [comment]
This is not a bug, you're missing the authority to load the assignments. We just forgot to add that authority after updating, I'll ping Willem since I cannot fix that on prod.

**Comment by tkgroot** [comment]
thanks for the clarification.

**Comment by timsmelik** [comment]
FYI: Caused by [this change](https://github.com/flock-community/flock-eco-workday/commit/6cced467441929b6eb11f6f6ef5b784fe93378a3#diff-c52dace17a37b2791b7c5a97c3cbde8cd07cddc588eef2f6fdb057ff8ec49076L34)

**Comment by wilmveel** [comment]
I have assigned the role to all users
